name: Copilot Chief Agent CI

on:
  push:
    paths:
      - 'extensions/copilot-chief-agent/**'
      - '.github/workflows/publish-copilot-chief-agent.yml'
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  package:
    if: ${{ !contains(github.event.head_commit.message, '[skip-agent]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install tooling
        run: |
          npm install -g @vscode/vsce

      - name: Get current version & last tag
        id: meta
        run: |
          CURR=$(jq -r .version extensions/copilot-chief-agent/package.json)
          echo "current=$CURR" >> $GITHUB_OUTPUT
          LAST_TAG=$(git describe --tags --abbrev=0 --match 'copilot-chief-agent-v*' 2>/dev/null || echo '')
          echo "last_tag=$LAST_TAG" >> $GITHUB_OUTPUT

      - name: Always auto bump patch
        id: bump
        run: |
          set -e
          CURR=${{ steps.meta.outputs.current }}
          IFS='.' read -r MA MI PA <<< "$CURR"
          PA=$((PA+1))
          NEW="$MA.$MI.$PA"
            jq ".version=\"$NEW\"" extensions/copilot-chief-agent/package.json > tmp.$$ && mv tmp.$$ extensions/copilot-chief-agent/package.json
          echo "version=$NEW" >> $GITHUB_OUTPUT
          echo "Bumped version to $NEW"
          git config user.name 'agent-bot'
          git config user.email 'agent-bot@users.noreply.github.com'
          git add extensions/copilot-chief-agent/package.json
          git commit -m "chore(agent): auto bump version to $NEW [skip-agent]" || echo 'No commit'
          git push || echo 'Push skipped'

      - name: Install dependencies (extension)
        working-directory: extensions/copilot-chief-agent
        run: npm install --no-audit --no-fund || true

      - name: Generate changelog section
        id: changelog
        run: |
          NEW_VER=${{ steps.bump.outputs.version }}
          LAST_TAG=${{ steps.meta.outputs.last_tag }}
          RANGE=""
          if [ -n "$LAST_TAG" ]; then RANGE="$LAST_TAG..HEAD"; fi
          LOG=$(git log $RANGE --pretty=format:'* %s (%h)' -- extensions/copilot-chief-agent || true)
          [ -z "$LOG" ] && LOG='* Cambios menores internos'
          {
            echo 'notes<<EOF'
            echo "## v$NEW_VER - $(date +%Y-%m-%d)"
            echo "$LOG"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
          printf "## v%s - %s\n%s\n\n" "$NEW_VER" "$(date +%Y-%m-%d)" "$LOG" >> extensions/copilot-chief-agent/CHANGELOG.md
          git add extensions/copilot-chief-agent/CHANGELOG.md || true
          git commit -m "docs(agent): update changelog v$NEW_VER [skip-agent]" || echo 'No changelog commit'
          git push || echo 'Skip push'

      - name: Sync repository after internal pushes
        run: |
          git fetch origin
          git checkout main
          git reset --hard origin/main
          echo "Post-sync HEAD: $(git rev-parse HEAD)"

      - name: Read final version
        id: finalver
        run: |
          FINAL=$(jq -r .version extensions/copilot-chief-agent/package.json)
          echo "version=$FINAL" >> $GITHUB_OUTPUT
          echo "Final version: $FINAL"

      - name: Create tag (if not exists)
        run: |
          VER=${{ steps.finalver.outputs.version }}
          TAG="copilot-chief-agent-v$VER"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG ya existe";
          else
            git tag "$TAG"
            git push origin "$TAG"
          fi

      - name: Package VSIX
        working-directory: extensions/copilot-chief-agent
        run: vsce package --no-yarn

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: copilot-chief-agent-vsix
          path: extensions/copilot-chief-agent/*.vsix

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: copilot-chief-agent-v${{ steps.finalver.outputs.version }}
          name: Copilot Chief Agent v${{ steps.finalver.outputs.version }}
          body: ${{ steps.changelog.outputs.notes }}
          files: extensions/copilot-chief-agent/*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
